### ISSUE TITLE
full documentation of architecture of skyring stack

### ISSUE THREAD

**Issue by mbukatov** [skyrings/skyring#14]
There should be an overview of skyring stack which would include:
- listing all services involved, it's purpose in the stack, and relations
  and dependencies among them
- for each service involved, list configuration files, log files and endpoints
  (such as open sockets)

The target audience would be both admins trying to troubleshoot skyring and developers trying to understand the stack before going deeper in the code.

**Comment by mbukatov** [comment]
ping

**Comment by mbukatov** [comment]
ping

**Comment by shtripat** [comment]
Updated the wiki page with architecture details and details about various components

**Comment by mbukatov** [comment]
[Wiki page](https://github.com/skyrings/skyring/wiki) contains overview of skyring stack.
